# Generated by Django 2.1.5 on 2020-01-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0004_auto_20200130_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
