# Generated by Django 2.1.5 on 2020-01-30 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20200130_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
