# Generated by Django 2.1.5 on 2020-01-30 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20200130_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
